apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - base/namespace.yaml
  - https://github.com/external-secrets/external-secrets/releases/download/v0.7.2/external-secrets.yaml
