apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-ccm
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: digitalocean
    creationPolicy: Merge
  dataFrom:
    - extract:
        key: /digitalocean-ccm
