---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
  namespace: external-secrets
stringData:
  secretId: ${secret_id}
