on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@just
      - uses: terraform-linters/setup-tflint@v2
      - uses: hashicorp/setup-terraform@v2
      - uses: hashicorp/setup-packer@main
      - run: apt install -y shellcheck

      - run: just init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: just ci
