on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@just
      - uses: terraform-linters/setup-tflint@v2
      - uses: hashicorp/setup-terraform@v2
      - uses: hashicorp/setup-packer@main

      - run: just init
      - run: just ci
