on:
  push:
    branches: [main]
    paths:
      - 'vault/**'

jobs:
  packer:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@just
      - uses: hashicorp/setup-packer@main

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ github.run_id }}

      - run: packer init
        working-directory: vault

      - run: just sub vault image
